sampledddapp/Banking.Web/Controllers/BalanceEnquiryController.cs
using AutoMapper;
using Banking.Model.Models;
using Banking.Service;
using Banking.Web.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Banking.Web.Controllers
{
    [Authorize]
    public class BalanceEnquiryController : Controller
    {
        private IBankAccountService _bankAccountService;
        private ITransactionService _transactionService;

        public BalanceEnquiryController(IBankAccountService bankAccountService, ITransactionService transactionService)
        {
            this._bankAccountService = bankAccountService;
            this._transactionService = transactionService;
        }

        #region Check Account Balance
        // GET: BalanceEnquiry
        public ActionResult CheckAccountBalance()
        {

            BankAccount accountBalanceInfo = this._bankAccountService.AccountDetailsByUserName(User.Identity.Name);
            BankAccountViewModel bankAccountViewModel = Mapper.Map<BankAccount, BankAccountViewModel>(accountBalanceInfo);           
            return View(bankAccountViewModel);
        }

        //Post
        [HttpPost]
        public ActionResult CheckAccountBalance(BankAccountViewModel bankAccountViewModel)
        {
            BankAccount bankAccount = Mapper.Map<BankAccountViewModel, BankAccount>(bankAccountViewModel);
            BankAccount accountBalanceInfo = this._bankAccountService.AccountDetails(bankAccount);
            if (accountBalanceInfo == null)
            {
                ViewBag.NoAccount = "NotFound";
                ViewBag.AccountInfo = new BankAccount();
            }
            else
                ViewBag.AccountInfo = accountBalanceInfo;
            return View();
        }
        #endregion

        #region Mini statement
        public ActionResult MiniStatement()
        {
            BankAccount accountBalanceInfo = this._bankAccountService.AccountDetailsByUserName(User.Identity.Name);
            BankAccountViewModel bankAccountViewModel = Mapper.Map<BankAccount, BankAccountViewModel>(accountBalanceInfo);
            return View(bankAccountViewModel);
        }
        [HttpPost]
        public ActionResult MiniStatement(BankAccountViewModel bankAccountViewModel)
        {
            BankAccount bankAccount = Mapper.Map<BankAccountViewModel, BankAccount>(bankAccountViewModel);
            var accountDetails = this._bankAccountService.AccountDetails(bankAccount);
            if (accountDetails != null)
            {
                ViewBag.LoggedAccount = accountDetails.Id;
                List<Transaction> result = this._transactionService.GetMiniStatement(accountDetails.Id);
                List<TransactionViewModel> miniStatement = Mapper.Map<List<Transaction>, List<TransactionViewModel>>(result);
                ViewBag.Transactions = miniStatement;
            }
            else
            {
                ViewBag.NoAccount = "NotFound";
                ViewBag.Transactions = new List<Transaction>();
            }
            return View();
        }
        #endregion
    }
}

sampledddapp/Banking.Web/Controllers/HomeController.cs
using Banking.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Banking.Web.Controllers
{
    public class HomeController : Controller
    {
       
       // private readonly IBankAccountService _bankAccountService;
        public HomeController(IBankAccountService bankAccountService)
        {
           // _bankAccountService = bankAccountService;
        }
        [Authorize]
        public ActionResult Index()
        {
            //_bankAccountService.BankAccount();
            return View();
        }

        
    }
}

sampledddapp/Banking.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

sampledddapp/Banking.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

sampledddapp/Banking.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<style type="text/css">
    .navBardemoBasicUsage md-content .ext-content {
        padding: 50px;
        margin: 20px;
        background-color: #FFF2E0;
    }
</style>
<div class="jumbotron">
    <h1>World Bank</h1>
    <p class="lead">Welcome to World Bank.</p>
    @*<p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>
<div ng-controller="BankingAppHomeCtrl" ng-cloak>
    <md-content>
        <md-tabs md-dynamic-height md-border-bottom>
            <md-tab label="Check Balance">
                <md-content class="md-padding">
                    
                    <p>
                        To check your account balance, click @Html.ActionLink("here", "CheckAccountBalance", "BalanceEnquiry")
                    </p>
                </md-content>
            </md-tab>
            <md-tab label="Bank Statements">
                <md-content class="md-padding">
                   
                    <p>To get your last five transactions, click @Html.ActionLink("here", "MiniStatement", "BalanceEnquiry")</p>
                </md-content>
            </md-tab>
            <md-tab label="Transaction">
                <md-content class="md-padding">

                   
                    <p>To deposit money to your account, click @Html.ActionLink("here", "DepositMoney", "Transaction")</p>
                    <p>To transfer money to other account, click @Html.ActionLink("here", "TransferMoney", "Transaction")</p>
                    <p>To withdraw money, click @Html.ActionLink("here", "WithdrawMoney", "Transaction")</p>
                </md-content>
            </md-tab>
        </md-tabs>
    </md-content>
</div>

@section scripts{
    <script>
        (function () {
            'use strict';

            bankingApp
                .controller('BankingAppHomeCtrl', BankingAppHomeCtrl);

            function BankingAppHomeCtrl($scope) {
                $scope.currentNavItem = 'page1';
            }
        })();
    </script>

}